// LOGIN Actions Constants

export const SET_SOCKET = "SET_SOCKET";
export const ACCOUNT_CREATED = "ACCOUNT_CREATED";
export const ACCOUNT_CREATED_FAIL = "ACCOUNT_CREATED_FAIL";
export const ACCOUNT_LOGIN = "ACCOUNT_LOGIN";
export const ACCOUNT_LOGIN_FAIL = "ACCOUNT_LOGIN_FAIL";


// API Actions Constants

export const GROUPS_LOADED = "GROUPS_LOADED";
export const GROUPS_LOADED_FAIL = "GROUPS_LOADED_FAIL";
export const FORM_CREATED = "FORM_CREATED";
export const FORM_CREATED_FAIL = "FORM_CREATED_FAIL";